"""add foreign key on user_health_profiles

Revision ID: 174203e25ac3
Revises: 28b58d42d4c0
Create Date: 2026-02-05 19:47:38.641457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174203e25ac3'
down_revision: Union[str, None] = '28b58d42d4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_health_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_health_profiles', type_='foreignkey')
    # ### end Alembic commands ###
