"""add lab tables

Revision ID: 247cb49dbe1c
Revises: 233c5016385d
Create Date: 2026-02-05 22:01:44.605892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '247cb49dbe1c'
down_revision: Union[str, None] = '233c5016385d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab_panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('biomarkers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('tier_included', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lab_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('code_prefix', sa.String(length=8), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_prefix')
    )
    op.create_table('lab_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('panel_id', sa.UUID(), nullable=False),
    sa.Column('order_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent_to_lab', 'sample_collected', 'processing', 'completed', 'cancelled', name='order_status'), nullable=False),
    sa.Column('lab_partner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_partner_id'], ['lab_partners.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['lab_panels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_order_code'), 'lab_orders', ['order_code'], unique=True)
    op.create_index(op.f('ix_lab_orders_user_id'), 'lab_orders', ['user_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('pdf_storage_key', sa.String(length=512), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'extracted', 'review_needed', 'verified', 'failed', name='processing_status'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=256), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_user_id'), 'lab_results', ['user_id'], unique=False)
    op.create_table('lab_biomarker_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('result_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('biomarker_code', sa.String(length=64), nullable=False),
    sa.Column('biomarker_name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('reference_range_low', sa.Float(), nullable=True),
    sa.Column('reference_range_high', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('normal', 'borderline', 'flagged', name='biomarker_status'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['lab_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_biomarker_user_code_date', 'lab_biomarker_values', ['user_id', 'biomarker_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_biomarker_user_code_date', table_name='lab_biomarker_values')
    op.drop_table('lab_biomarker_values')
    op.drop_index(op.f('ix_lab_results_user_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_lab_orders_user_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_order_code'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_table('lab_partners')
    op.drop_table('lab_panels')
    # ### end Alembic commands ###
