"""add_garmin_tables

Revision ID: b1c4eb901eac
Revises: 247cb49dbe1c
Create Date: 2026-02-06 09:45:01.829586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c4eb901eac'
down_revision: Union[str, None] = '247cb49dbe1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garmin_connections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('garmin_user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_garmin_connections_garmin_user_id'), 'garmin_connections', ['garmin_user_id'], unique=True)
    op.create_table('garmin_data_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_type', 'date', name='uq_garmin_user_type_date')
    )
    op.create_index(op.f('ix_garmin_data_points_user_id'), 'garmin_data_points', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garmin_data_points_user_id'), table_name='garmin_data_points')
    op.drop_table('garmin_data_points')
    op.drop_index(op.f('ix_garmin_connections_garmin_user_id'), table_name='garmin_connections')
    op.drop_table('garmin_connections')
    # ### end Alembic commands ###
